#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Wed May 28 01:56:03 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PokeFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PokeFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_2_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Save", "", wx.ITEM_NORMAL)
        self.frame_2_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_2_menubar)
        # Menu Bar end
        self.choice_1 = wx.Choice(self, wx.ID_ANY, choices=["Choice0"])
        self.spin_ctrl_1 = wx.SpinCtrl(self, wx.ID_ANY, "", min=0, max=100)
        self.isWildCheckBox = wx.CheckBox(self, wx.ID_ANY, "wild?")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Add")
        self.button_2 = wx.Button(self, wx.ID_ANY, "Defeat")
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PokeFrame.__set_properties
        self.SetTitle("frame_2")
        self.SetSize((800, 400))
        self.choice_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PokeFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.choice_1, 0, 0, 0)
        sizer_3.Add(self.spin_ctrl_1, 0, 0, 0)
        sizer_3.Add(self.isWildCheckBox, 0, 0, 0)
        sizer_3.Add(self.button_1, 0, 0, 0)
        sizer_3.Add(self.button_2, 0, 0, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_2.Add(sizer_1, 0, wx.EXPAND, 0)
        sizer_4.Add(self.text_ctrl_2, 1, 0, 0)
        sizer_4.Add(self.text_ctrl_3, 1, 0, 0)
        sizer_4.Add(self.text_ctrl_4, 1, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class PokeFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.App(False)
    wx.InitAllImageHandlers()
    frame_1 = PokeFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()